### ISSUE TITLE
Create a new module for storing REST configuratiosn

### ISSUE THREAD

**Issue by AliAkberAakash** [AliAkberAakash/leafy#27]
Tasks:
- [ ] Create a new module named `network` directly under `leafy`.
- [ ] Create a new folder named `rest` under `network` module. ex: `network/lib/rest`
- [ ] Cleanup the pubspec file in `network` and add dependency on `dio`. Use a fixed version.
- [ ] Add dependency on `getIt`. Use the same version from `leafy`.

**Comment by muhib349** [comment]
Missed the rest folder to add, adding it to next issue

**Comment by AliAkberAakash** [comment]
You can add it while fixing the feedbacks @muhib349

**Comment by AliAkberAakash** [comment]
Closed in #29
